### ISSUE TITLE
Server crashes

### ISSUE THREAD

**Issue by Luxaria-source** [ZeroNoRyouki/ExtremeReactors2#129]
My server keeps on crashing due to this issue.

Description: Exception in server tick loop

java.util.NoSuchElementException: null
    at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:159) ~[guava-31.1-jre.jar%2374!/:?] {}
    at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.FuelRodsMap.getNextIrradiationSource(FuelRodsMap.java:96) ~[**ExtremeReactors2-1.20.1-2.0.75.jar%23478!/:1.20.1-2.0.75**] {re:classloading}
    at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.MultiblockReactor.getNextIrradiationSource(MultiblockReactor.java:349) ~[ExtremeReactors2-1.20.1-2.0.75.jar%23478!/:1.20.1-2.0.75] {re:classloading}
    at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.ReactorLogic.performIrradiation(ReactorLogic.java:221) ~[ExtremeReactors2-1.20.1-2.0.75.jar%23478!/:1.20.1-2.0.75] {re:classloading}
    at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.ReactorLogic.update(ReactorLogic.java:79) ~[ExtremeReactors2-1.20.1-2.0.75.jar%23478!/:1.20.1-2.0.75] {re:classloading}
    at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.MultiblockReactor.updateServer(MultiblockReactor.java:985) ~[ExtremeReactors2-1.20.1-2.0.75.jar%23478!/:1.20.1-2.0.75] {re:classloading}

**Comment by ZeroNoRyouki** [comment]
Post the full crash log please

**Comment by Luxaria-source** [comment]
https://pastebin.com/W3frM9G7

> Post the full crash log please

**Comment by ZeroNoRyouki** [comment]
Link already expired. Could you please repost it with a longer "timeout" ?
Thanks
Z
