### ISSUE TITLE
Reactors crash log

### ISSUE THREAD

**Issue by funnycubeguy** [ZeroNoRyouki/ExtremeReactors2#138]
Running 1.20.1 atm9 the reactors crashed my server.

```Time: 2023-12-27 11:21:10
Description: Exception in server tick loop

java.util.NoSuchElementException: null
	at com.google.common.collect.AbstractIterator.next(AbstractIterator.java:159) ~[guava-31.1-jre.jar%23147!/:?] {re:mixin}
	at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.FuelRodsMap.getNextIrradiationSource(FuelRodsMap.java:96) ~[ExtremeReactors2-1.20.1-2.0.77.jar%23726!/:1.20.1-2.0.77] {re:classloading}
	at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.MultiblockReactor.getNextIrradiationSource(MultiblockReactor.java:349) ~[ExtremeReactors2-1.20.1-2.0.77.jar%23726!/:1.20.1-2.0.77] {re:classloading}
	at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.ReactorLogic.performIrradiation(ReactorLogic.java:221) ~[ExtremeReactors2-1.20.1-2.0.77.jar%23726!/:1.20.1-2.0.77] {re:classloading}
	at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.ReactorLogic.update(ReactorLogic.java:79) ~[ExtremeReactors2-1.20.1-2.0.77.jar%23726!/:1.20.1-2.0.77] {re:classloading}
	at it.zerono.mods.extremereactors.gamecontent.multiblock.reactor.MultiblockReactor.updateServer(MultiblockReactor.java:986) ~[ExtremeReactors2-1.20.1-2.0.77.jar%23726!/:1.20.1-2.0.77] {re:classloading}
	at it.zerono.mods.zerocore.lib.multiblock.AbstractMultiblockController.updateMultiblockEntity(AbstractMultiblockController.java:537) ~[ZeroCore2-1.20.1-2.1.41.jar%23980!/:1.20.1-2.1.41] {re:classloading}
	at it.zerono.mods.zerocore.lib.multiblock.registry.MultiblockWorldRegistry.tickStart(MultiblockWorldRegistry.java:118) ~[ZeroCore2-1.20.1-2.1.41.jar%23980!/:1.20.1-2.1.41] {re:classloading}
	at it.zerono.mods.zerocore.lib.multiblock.registry.MultiblockRegistry.tickStart(MultiblockRegistry.java:162) ~[ZeroCore2-1.20.1-2.1.41.jar%23980!/:1.20.1-2.1.41] {re:classloading}
	at it.zerono.mods.zerocore.lib.multiblock.registry.MultiblockRegistry.onWorldTick(MultiblockRegistry.java:197) ~[ZeroCore2-1.20.1-2.1.41.jar%23980!/:1.20.1-2.1.41] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:263) ~[eventbus-6.0.5.jar%23145!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:255) ~[eventbus-6.0.5.jar%23145!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:319) ~[eventbus-6.0.5.jar%23145!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:299) ~[eventbus-6.0.5.jar%23145!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:952) ~[forge-1.20.1-47.2.17-universal.jar%23987!/:?] {re:mixin,re:classloading,pl:mixin:APP:aether.mixins.json:common.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1155) ~[server-1.20.1-20230612.114412-srg.jar%23982!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23982!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23982!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23982!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23982!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:gtceu-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:dankstorage.mixins.json:MinecraftServerAccess,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}```

**Comment by ZeroNoRyouki** [comment]
When did this happened?
