### ISSUE TITLE
[1.19] Mod does not load with forge .22+ due to fluid API changes

### ISSUE THREAD

**Issue by Saereth** [ZeroNoRyouki/ExtremeReactors2#87]
Logfile:
https://www.toptal.com/developers/hastebin/izadidozaf.yaml

Relevant code snip:
```
[21:45:39] [Render thread/ERROR]: Caught exception during event RegisterEvent dispatch for modid bigreactors
java.lang.NoClassDefFoundError: net/minecraftforge/fluids/FluidAttributes
	at it.zerono.mods.extremereactors.gamecontent.fluid.SteamFluid.<init>(SteamFluid.java:72) ~[ExtremeReactors2-1.19-2.0.46.jar%23110!/:1.19-2.0.46]
	at it.zerono.mods.extremereactors.gamecontent.fluid.SteamFluid$Source.<init>(SteamFluid.java:54) ~[ExtremeReactors2-1.19-2.0.46.jar%23110!/:1.19-2.0.46]
	at net.minecraftforge.registries.DeferredRegister.lambda$addEntries$1(DeferredRegister.java:388) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.registries.RegisterEvent.register(RegisterEvent.java:59) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.registries.DeferredRegister.addEntries(DeferredRegister.java:388) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.registries.DeferredRegister$EventDispatcher.handleEvent(DeferredRegister.java:330) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.registries.__EventDispatcher_handleEvent_RegisterEvent.invoke(.dynamic) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:93) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-6.0.0.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:107) ~[javafmllanguage-1.19-41.0.38.jar%23189!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$postEventWithWrap$35(ModLoader.java:309) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at net.minecraftforge.fml.ModList.forEachModContainer(ModList.java:218) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at net.minecraftforge.fml.ModLoader.postEventWithWrap(ModLoader.java:307) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at net.minecraftforge.registries.GameData.postRegisterEvents(GameData.java:321) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.common.ForgeStatesProvider.lambda$new$4(ForgeStatesProvider.java:25) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$23(ModLoader.java:201) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:201) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$14(ModLoader.java:179) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:179) ~[fmlcore-1.19-41.0.38.jar%23188!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$begin$1(ClientModLoader.java:92) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.lambda$createRunnableWithCatch$4(ClientModLoader.java:112) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraftforge.client.loading.ClientModLoader.begin(ClientModLoader.java:92) ~[forge-1.19-41.0.38-universal.jar%23192!/:?]
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:454) ~[client-1.19-20220607.102129-srg.jar%23187!/:?]
	at net.minecraft.client.main.Main.main(Main.java:169) ~[client-1.19-20220607.102129-srg.jar%23187!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19-41.0.38.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.1.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:155) [bootstraplauncher-1.1.0.jar:?]
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.fluids.FluidAttributes
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-1.0.5.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 41 more
```

ExtremeReactors2-1.19-2.0.46
ZeroCore2-1.19-2.1.19
MC 1.19
Forge 41.0.38

**Comment by ZeroNoRyouki** [comment]
I know, stay with forge .21 for now

**Comment by ZeroNoRyouki** [comment]
1.19-2.0.47 is compatible with the new Fluid API

**Comment by Saereth** [comment]
ty!
